name: GSI-Workshop3

on:
    
env:
  ROM_URL: http://bigota.d.miui.com/20.4.27/miui_MIMIX3_20.4.27_8f7879221b_10.0.zip
  ROM_NAME: MIUI
  BUILD_TYPE: all
  TZ: Asia/Dhaka

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements with GSI Workshop setup script
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir upload
              zip -r GSI.zip ./*
              if [[ $(du -sb "GSI.zip" | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - "GSI.zip" | split -d -b 1024m - "upload/GSI.zip"
              else
                  mv GSI.zip upload/
              fi
              ls "upload"                  
              
       - name: Upload GSI to action-release.
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}/ErfanGSIs/output/upload/*
           name: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}
           tag: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ github.run_number }}
           token: ${{ secrets.GHP }}

         
            
